CREATE TABLE tx_aisteahelpdesk_domain_model_ticket (
  uid int(11) NOT NULL auto_increment,
  pid int(11) NOT NULL DEFAULT '0',
  tstamp int(11) unsigned NOT NULL DEFAULT '0',
  crdate int(11) unsigned NOT NULL DEFAULT '0',
  cruser_id int(11) unsigned NOT NULL DEFAULT '0',
  deleted smallint(5) unsigned NOT NULL DEFAULT '0',
  hidden smallint(5) unsigned NOT NULL DEFAULT '0',
  sorting int(11) unsigned NOT NULL DEFAULT '0',
  ticket_number varchar(64) NOT NULL DEFAULT '',
  subject varchar(255) NOT NULL DEFAULT '',
  description text,
  customer_name varchar(255) NOT NULL DEFAULT '',
  customer_email varchar(255) NOT NULL DEFAULT '',
  customer_fe_user int(11) unsigned NOT NULL DEFAULT '0',
  assigned_backend_user int(11) unsigned NOT NULL DEFAULT '0',
  visibility_token varchar(80) NOT NULL DEFAULT '',
  site_root_page_id int(11) unsigned NOT NULL DEFAULT '0',
  site_language int(11) unsigned NOT NULL DEFAULT '0',
  category int(11) unsigned NOT NULL DEFAULT '0',
  priority int(11) unsigned NOT NULL DEFAULT '0',
  status int(11) unsigned NOT NULL DEFAULT '0',
  due_at int(11) unsigned NOT NULL DEFAULT '0',
  first_response_at int(11) unsigned NOT NULL DEFAULT '0',
  resolved_at int(11) unsigned NOT NULL DEFAULT '0',
  closed_at int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY ticket_number (ticket_number),
  KEY customer_fe_user (customer_fe_user),
  KEY status (status)
);

CREATE TABLE tx_aisteahelpdesk_domain_model_ticketmessage (
  uid int(11) NOT NULL auto_increment,
  pid int(11) NOT NULL DEFAULT '0',
  tstamp int(11) unsigned NOT NULL DEFAULT '0',
  crdate int(11) unsigned NOT NULL DEFAULT '0',
  cruser_id int(11) unsigned NOT NULL DEFAULT '0',
  deleted smallint(5) unsigned NOT NULL DEFAULT '0',
  hidden smallint(5) unsigned NOT NULL DEFAULT '0',
  sorting int(11) unsigned NOT NULL DEFAULT '0',
  ticket int(11) unsigned NOT NULL DEFAULT '0',
  author_type varchar(20) NOT NULL DEFAULT '',
  author_name varchar(255) NOT NULL DEFAULT '',
  author_email varchar(255) NOT NULL DEFAULT '',
  author_fe_user int(11) unsigned NOT NULL DEFAULT '0',
  author_be_user int(11) unsigned NOT NULL DEFAULT '0',
  message text,
  is_internal smallint(5) unsigned NOT NULL DEFAULT '0',
  attachments int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY ticket (ticket),
  KEY is_internal (is_internal)
);

CREATE TABLE tx_aisteahelpdesk_domain_model_ticketcategory (
  uid int(11) NOT NULL auto_increment,
  pid int(11) NOT NULL DEFAULT '0',
  tstamp int(11) unsigned NOT NULL DEFAULT '0',
  crdate int(11) unsigned NOT NULL DEFAULT '0',
  cruser_id int(11) unsigned NOT NULL DEFAULT '0',
  deleted smallint(5) unsigned NOT NULL DEFAULT '0',
  hidden smallint(5) unsigned NOT NULL DEFAULT '0',
  sorting int(11) unsigned NOT NULL DEFAULT '0',
  title varchar(255) NOT NULL DEFAULT '',
  slug varchar(255) NOT NULL DEFAULT '',
  is_active smallint(5) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (uid),
  KEY parent (pid)
);

CREATE TABLE tx_aisteahelpdesk_domain_model_ticketpriority (
  uid int(11) NOT NULL auto_increment,
  pid int(11) NOT NULL DEFAULT '0',
  tstamp int(11) unsigned NOT NULL DEFAULT '0',
  crdate int(11) unsigned NOT NULL DEFAULT '0',
  cruser_id int(11) unsigned NOT NULL DEFAULT '0',
  deleted smallint(5) unsigned NOT NULL DEFAULT '0',
  hidden smallint(5) unsigned NOT NULL DEFAULT '0',
  sorting int(11) unsigned NOT NULL DEFAULT '0',
  title varchar(255) NOT NULL DEFAULT '',
  code varchar(64) NOT NULL DEFAULT '',
  response_hours int(11) unsigned NOT NULL DEFAULT '0',
  resolve_hours int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (uid),
  KEY parent (pid)
);

CREATE TABLE tx_aisteahelpdesk_domain_model_ticketstatus (
  uid int(11) NOT NULL auto_increment,
  pid int(11) NOT NULL DEFAULT '0',
  tstamp int(11) unsigned NOT NULL DEFAULT '0',
  crdate int(11) unsigned NOT NULL DEFAULT '0',
  cruser_id int(11) unsigned NOT NULL DEFAULT '0',
  deleted smallint(5) unsigned NOT NULL DEFAULT '0',
  hidden smallint(5) unsigned NOT NULL DEFAULT '0',
  sorting int(11) unsigned NOT NULL DEFAULT '0',
  title varchar(255) NOT NULL DEFAULT '',
  code varchar(64) NOT NULL DEFAULT '',
  is_closed smallint(5) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (uid),
  KEY parent (pid)
);
